project:
  type: website
  output-dir: docs

website:
  title: ""
  twitter-card: true
  open-graph: true
  navbar:
    logo: "images/ISREStarburstTextWhiteNavBar.png"
    logo-alt: "ISRE 2024 Belfast Logo"
    left:
      - href: index.qmd
        text: Home
      - importantdates.qmd
      - keynotes/index.qmd
      - sponsorspage/index.qmd
      - program/index.qmd
      - location/index.qmd
      - accommodation/index.qmd
      - registration/index.qmd
      - preconference/index.qmd
      # - safetyatQUB/index.qmd
      - contactus/index.qmd

format:
  html:
    theme: 
      - cerulean
      - custom.scss
    toc: true
    page-layout: full
    
filters:
   - lightbox
   
editor: visual

