project:
  type: website

website:
  title: "ISRE 2024"
  navbar:
    logo: "images/logo.png"
    left:
      - href: index.qmd
        text: Home
      - importantdates.qmd
      - invitedkeynotes.qmd

format:
  html:
    theme: 
      - simplex
      - custom.scss
    toc: true
    page-layout: full
    

editor: visual

