project:
  type: website
  output-dir: docs

website:
  title: ""
  favicon: images/favicon.png
  twitter-card:
    title: "ISRE 2024 Belfast"
    creator: "@gmckeown"
  open-graph:
    site-name: "ISRE 2024 Belfast"
  google-analytics: "G-33PP5XPV1R"
  site-url: https://isre2024.org
  navbar:
    logo: "images/ISREStarburstTextWhiteNavBar.png"
    logo-alt: "ISRE 2024 Belfast Logo"
    left:
      - importantdates.qmd
      - keynotes/index.qmd
      - text: "Submit"
        menu:
          - text: "Submit"
            href: submissions/submissions.qmd
          - text: "Register"
            href: registration/index.qmd
      - sponsorspage/index.qmd
      - people/people.qmd
      - program/index.qmd
      - accommodation/index.qmd
      - preconference/index.qmd
      # - safetyatQUB/index.qmd
      - text: "Location"
        menu:
          - text: "Queen's University Belfast"
            href: location/Queens.qmd
          - text: "Belfast City"
            href: location/Belfast.qmd
          - text: "Banquet"
            href: location/TitanicBelfast.qmd
      - contactus/index.qmd
format:
  html:
    theme: 
      - cerulean
      - custom.scss
    smooth-scroll: true
    toc: false
    page-layout: full
    
resources:
  - CNAME
