project:
  type: website
  output-dir: docs

website:
  title: "ISRE 2024: Conference of the International Society for Research on Emotion"
  favicon: images/favicon.png
  twitter-card:
    title: "ISRE 2024 Belfast"
    creator: "@gmckeown"
  open-graph:
    site-name: "ISRE 2024 Belfast"
  google-analytics: "G-33PP5XPV1R"
  site-url: https://isre2024.org
  navbar:
    title: false
    logo: "images/ISREStarburstTextWhiteNavBar.png"
    left:
      - importantdates.qmd
      - keynotes/index.qmd
      - text: "Register"
        href: registration/index.qmd
      - sponsorspage/index.qmd
      - text: "People"
        href: people/people.qmd
      - program/index.qmd
      - text: "ISRE Challenge"
        href: https://www.isre.org/news/668358/A-New-ISRE-Initiative---Emotion-Express-One-Minute-to-Inspire.htm
      - text: Preconferences
        menu: 
          - href: preconference/list/affective_computing.qmd
            text: "Affective Computing"
          - href: preconference/list/cross_species.qmd
            text: "Cross-Species Emotion Research"
          - href: preconference/list/experience_regulation.qmd
            text: "Emotion Regulation in Online Contexts"
          - href: preconference/list/emotions_relationships.qmd
            text: "Emotions in Interpersonal Relationships"
          - href: preconference/list/engaging_suffering.qmd
            text: "Engaging with Other People's Suffering"
          - href: preconference/list/emotional_development.qmd
            text: "Language and Emotional Development"
          - href: preconference/list/laughter_workshop.qmd
            text: "Laughter and Other Non-Verbal Vocalisations"
      # - safetyatQUB/index.qmd
      - text: "Location"
        menu:
          - text: "Queen's University Belfast"
            href: location/Queens.qmd
          - text: "Belfast City"
            href: location/Belfast.qmd
          - text: "Opening Reception"
            href: location/Stormont.qmd
          - text: "Banquet"
            href: location/TitanicBelfast.qmd
          - text: "Accomodation"
            href: accommodation/index.qmd
      - contactus/index.qmd
  page-footer:
    # left: "Powered by [Quarto](https://quarto.org/) v1.3.24"
    background: "#D6000D"
    center:
      - href: https://www.isre.org/
        icon: globe
        aria-label: Website
      - href: https://twitter.com/isreorg
        icon: twitter
        aria-label: Twitter
      - href: https://www.facebook.com/IsreOrg/
        icon: facebook
        aria-label: Facebook
      - href: https://www.instagram.com/isre.ig/
        icon: instagram
        aria-label: Instagram
      
format:
  html:
    theme: [cerulean, custom.scss]
    mainfont: Montserrat
    css: styles.css
    smooth-scroll: true
    toc: false
    page-layout: full
    
resources:
  - CNAME
