---
title: "ISRE Awards"
---

We're excited to announce applications are open for our **Travel and Dissertation Awards at ISRE24**. These awards support scholars facing financial barriers and recognise exceptional doctoral research.

## Travel Award

We are offering a limited number of **£500 travel awards** to support students and postdoctoral researchers attending ISRE2024. **Applicants cannot have obtained an ISRE travel award at a previous ISRE meeting and must be graduate students or postdocs at the time of submission.** Applicants must be an author on a poster, individual or symposium oral presentation, or a flash presentation accepted at ISRE2024.
 
Those interested in these opportunities should submit their application to the ISRE2024 Organizers ([ISRE24@qub.ac.uk](mailto:ISRE24@qub.ac.uk) ) by **30 April 2024**.  Please title your email **“Travel Grant Application”**, indicate if you are a student or a postdoctoral researcher, include your CV and a 500-words maximum explanation of why you should be considered for the grant. Awards will be based on need and merit.

## Dissertation Award

Details to follow.