---
title: "Registration"
title-block-banner: true
---

## Registration System Open Now

Register here: **[https://ecommerce.apps.qub.ac.uk/osisre/catalog/index.php](https://ecommerce.apps.qub.ac.uk/osisre/catalog/index.php)**

- Economy rates apply to students, postdocs, and attendees affiliated with universities in [Low- to Middle-Income Countries](list_countries.qmd)
- Please note that all ISRE2024 food will be vegetarian

::: {.callout-warning title="Registration warning"}
- **Early registration ended 30 April 2024**

- **No refunds are possible after 20 June 2024**

- **Rooms in QUB Student Accommodation can be booked until 8 July 2024**

- **Please note that there can be no further admissions to the Welcome Reception on 17 July 2024**

- **Specific food requests can no longer be accommodated. For those who register late, a standard vegetarian meal will be provided.**

:::

## Main Conference Registration Fees (in GBP)

|   |   |
|---|---|
|~~Economy ISRE member early~~ |~~£300.00~~ |
|~~ISRE member early~~ |~~£375.00~~|
|~~Economy non-member early~~ |~~£400.00~~|
|~~Non-member early~~ |~~£475.00~~|
|   |   |
|Economy ISRE member regular |£350.00|
|ISRE member regular |£425.00|
|Economy non-member regular |£450.00|
|Non-member regular |£525.00|
|   |   |
|Economy ISRE member onsite |£450.00|
|ISRE member onsite | £525.00|
|Economy non-member onsite |£550.00|
|Non-member onsite |£625.00|
|   |   |
|Conference dinner |£50.00|

## Pre-conferences

|   |   |
|---|---|
|Pre-Conference fee if attending ISRE2024 |£75.00 |
|Pre-Conference only fee |£125.00|

## Guests

|   |   |
|---|---|
|Conference companion pass |£125.00|
|Additional conference dinner |£50.00|

