---
title: "Emotions in Interpersonal Relationships"
title-block-banner: true
---

Emotions are inherently social, in that they are heavily influenced by interactions with others. Most of the time, they arise, evolve, and are managed in the company of and by others, whose emotions, in turn, become impacted by us as well. Fortunately, there is a growing awareness of how intertwined emotions and interpersonal relationships are, and research on this topic is rapidly increasing. In light of this evolution, **this pre-conference focusses on emotions in the context of interpersonal relationships, with a particular emphasis on its dynamic nature**. It will feature a series of talks presenting cutting-edge research. **Keynotes** and **flash talks** will span across multiple domains, including a wide spectrum of emotions and interpersonal relationships, such as parent-child interactions, romantic relationships and leader-member exchanges. Keynote speakers (see below) are invited experts from different fields, ranging from broader social psychology to clinical and family science. Additionally, there will be a **debate** about the current state and future of the field, and we are honored to announce that prof. dr. Agneta Fischer will conclude this exciting day as a **discussant**. 

Through this program, we aim to exchange knowledge on the intricate ways in which emotions shape and are shaped by interpersonal relationships, and to identify key research gaps in this rapidly expanding field. Our goal is to bring together researchers from all stages and disciplines, fostering connection and interdisciplinary collaboration over this important topic.

We will be accepting abstract submissions for flash talk presentations (5-minute talks with 5 minutes for Q&A). Presentations should address the topic of emotions in the context of interpersonal relationships, preferably assessing research questions in a dynamic way. The abstract can be a maximum of 500 words and should outline the goals of the research, the methods used, and a summary of the results. Acceptance as a flash talk will be decided after review by the organizers, based on the fit with the main theme and with other talks. 

## Important dates

- Abstract submission: **20th of April 2024** (These can be submitted per email to **laura.sels@ugent.be**)
- Acceptance notification: **20th of May 2024**

## Organisation

- Laura Sels
- Lisanne Pauw 
- Tabea Springstein

## Confirmed Speakers

 - **Prof. Dr. Katharine Greenaway** (University of Melbourne) researches emotional antecedents to and consequences of social connection. She studies topics related to the spectrum of connections we have with others, from loneliness and secrecy to successful interpersonal emotion regulation and shared identity. In her talk, Katie will discuss emotion goals for experience and expression as a lens for understanding this range of social experiences.

- **Dr. Reuma Gadassi-Polack** (Tel Aviv-Yaffo Academic College & Yale University) examines the interpersonal and neurobiological basis of typical and atypical emotion regulation, with a special focus on depression development. Her current research deals with emotional reactions to social feedback from parents and peers during the transition to adolescence and the potential protective roles of emotion regulation and social interpretation flexibility. Dr. Gadassi-Polack will talk about how coming from the background of studying emotions in romantic relationships influenced her research on emotions in the parent-adolescent relationship.

- **Dr. Tammy English** (Washington University in St. Louis) conducts research on emotion and emotion regulation across adulthood from an interpersonal perspective. She studies the ways that social context and socially-oriented motives impact how emotions are managed in daily interactions, as well as the interrelationship between emotion regulation and social functioning. In her talk, Tammy will focus on emotion regulation in romantic relationships and novel ways to capture the dynamic interplay between partners that impact well-being.


- discussant: **Prof. Dr. Agneta Fischer** is Professor in Emotions and Affective Processes at the University of Amsterdam. Her broad research interest is emotions in social contexts, and she has published in the domain of facial expressions of emotion, emotional mimicry, culture and gender differences in emotions, social emotion regulation and the social functions of emotions. She will be the discussant in the symposium.