---
title: "Engaging with other people’s suffering: Emotion, Empathy, Eudaimonia and Curiosity."
title-block-banner: true
---

Whether through news, art, social media, or even in professional settings or walking on the street, people can be confronted with the suffering of others. Although other people’s suffering can evoke strong emotions (e.g., fear, outrage, sadness), people do not seem to consistently avoid such content. Engaging with the suffering of other people involves different psychological and affective processes. Through this preconference **we aim to bring together scholars from different disciplines (i.e., social psychology, media psychology, criminology, neuroscience) to discuss how their research can help understand when people do, and do not, engage with a suffering other**. How do people derive meaning from other people’s stories of suffering? Why do people seek out information that can evoke intense emotional reactions? When do people choose to experience empathy and when (and how) do they choose to regulate empathy? How do people respond to violent street incidents? Research on eudaimonia, empathy, curiosity and prosociality, will shed light on the affective processes, motives and outcomes of engaging with the suffering of others.

Our goal is to bring together both senior and junior researchers to discuss the theme of the preconference from different interdisciplinary perspectives. The program will include **5 invited speakers** (from different disciplines and regions) that will present their work in 45-minute talks, leaving plenty of time for questions and discussion. Moreover, the preconference will invite **submissions for short talks** (8 speakers of 15 minutes each).

## Confirmed speakers

**Anne Bartsch** (Leipzig University) specializes in research on media uses and effects, with a special focus on media entertainment and emotional media effects. Her current research deals with the appeal of moving and thought-provoking media experiences and with the effects of such experiences on individuals' issue involvement, information seeking, and political participation concerning the issues portrayed.

**Suzanne Oosterwijk** (University of Amsterdam) is interested in a phenomenon called morbid curiosity (i.e., seeking out images, videos, and stories that detail death, violence, or harm). She will discuss epistemic, eudaimonic, social and affective motives that may explain why people engage with emotionally evocative content.

**Daryl Cameron** (Pennsylvania State University) studies why and how people are motivated to empathetically engage with or avoid others' suffering. Decisions whether or not to share in others' experiences are based on how people consider costs and benefits of empathy and enact different emotion regulation strategies. He will summarize his work using the empathy selection task to explore motivated empathy regulation about suffering through the lens of situation selection.

**Lasana Harris** (University College London) studies dehumanised perception as a proactive emotion regulation strategy. His research demonstrates that people predict empathy requirements in impending social interactions and dehumanise when they expect the social interaction to be emotionally taxing. He will discuss research documenting that medical professions engage dehumanised perception to stave off burnout and facilitate better care for their patients.

**Marie Rosenkrantz Lindegaard** (Netherlands Institute for the Study of Crime and Law Enforcement) has a background in cultural anthropology and criminology. Her pioneering work on bystander behavior challenged the assumption that bystanders are passive agents, showing that intervention during conflicts, rather than apathy, is the norm.

## Organisation

Suzanne Oosterwijk, Anastassia Vivanco Carlevari, Yağmur Özbay, Esther Niehoff & Gerben van Kleef (University of Amsterdam)

## Duration: 1 day
