---
title: "Keep Calm and Regulate On(line)?"
subtitle: "Emotion regulation in online contexts and links to mental health and wellbeing"
title-block-banner: true
---

A growing body of research indicates that **social media use may be contributing to young people’s poor mental health around the world**. However, given the ubiquity of social media apps and their extensive integration into daily life, it is not viable to ask a young person to completely abstain from social media. Rather, a more pragmatic approach is to examine **psychological risk factors associated with social media use that might predispose some individuals to be at greater risk for experiencing poor mental health in the first place**.

This pre-conference will focus on the experience and regulation of emotions in online contexts (including social media apps) and attendant effects on mental health and wellbeing among youth and young adults. Specifically, the first talk will highlight links between use of screen media (overall) and social media (in particular), emotion regulation abilities, and wellbeing. The second talk will discuss neural correlates of emotion regulation, as measured by EEG, and links to adolescents’ preference for online (versus in-person) social interactions and social anxiety symptoms. The third talk demonstrates how machine learning methods can be applied to people’s music preferences on Spotify to establish digital “traces” of risk factors for depression and aid in early detection and prevention efforts for depression and other conditions. Collectively, the findings featured in this pre-conference represent a **promising and timely new avenue for the study of emotion regulation and the field of affective science more broadly**. 

In addition to the above-mentioned talks, the pre-conference will also feature a series of data blitz presentations by trainees and early career researchers and two keynote talks about the state of the field and implications for public policy and advocacy work. The event will conclude with a panel-style Q&A and to promote further discussion, professional networking, and potential research collaborations.

## Organisation

- Richard Lopez (Worcester Polytechnic Institute)
- Sarah Myruski (The Pennsylvania State University)

## Confirmed Speakers

- Beatriz Brandao (Rice University)
- Dr. Daria Kuss (**Keynote speaker**; Nottingham Trent University)
- Dr. Richard Lopez (Worcester Polytechnic Institute)
- Dr. Sarah Myruski (The Pennsylvania State University)
- Hannah Oertel (**Keynote speaker**; founder, Delay Smartphones)
- Dr. Corinna Perchtold-Stefan (University of Graz)
- Dr. Sergio Pirla (Aarhus University)

## Information and Agenda

Full schedule available on the [pre-conference website](https://sites.google.com/view/isre2024-emotion-regulation-pr/). 

For further information or questions regarding the preconference, please contact co-organizers Richard Lopez ([rlopez1@wpi.edu](mailto:rlopez1@wpi.edu)) and Sarah Myruski ([sfm6016@psu.edu](mailto:sfm6016@psu.edu)).

