---
title: "Instructions for Presenters"
---

## Oral Presentations & Flash Talks

For those giving Oral Presentations, you will be afforded a **12-minute slot for your talk and two minutes for any audience questions**. 

For a Flash Talk, you will be afforded **six minutes for your presentation and two minutes for brief questions**. We will maintain a strict schedule, and you can expect the next speaker to begin to set up as you take questions. 

Speakers can present using the computers in the rooms or their own laptops, and we will provide audio. In all rooms in the conference, the projection systems are in the 16:9 format.

Symposia will be moderated by the symposium organizers. Individual talks sessions will be assigned a moderator. Moderators will be communicated in the ISRE2024 program in the next weeks. For oral presentations, please make sure to contact your session moderator before your scheduled session. You may be asked to send your slides in advance. 


## Posters

You are strongly encouraged to set up posters in the morning before the first conference session. You are welcome to leave your poster up till the end of the day. The following are the guidelines for poster presentations:

- Poster size is limited to **121cm x 121cm** (4 x 4 ft, A0 format maximum). Landscape and portrait layouts are both supported. We will provide posterboards and stationery for attaching your poster.

- The boards will contain the **poster number** assigned to your poster so that you will know which board to use.

- Your poster must contain the abstract title and the name(s) of the poster author(s).

- QR codes may be included on posters and handouts so long as the code does not lead to a website or materials promoting or marketing a company or product 

- You should bear in mind that your illustrations will be viewed from distances of 3 feet or more. All lettering should be sized accordingly.

### Poster Printing Services in Belfast

You can find some local poster printing services below. Please contact them directly to
purchase posters.

#### Windsor Photoprints

- About 5 minutes’ walk from QUB
- Website: https://www.windsorphotoprints.co.uk/poster-printing
- Phone: +4428 9066 8831
- Email: windsorphotoprints@gmail.com
- Address: 130 Eglantine Ave, Belfast BT9 6EU
- Opening hours: 9am-5pm Monday to Friday, closed Saturdays and Sundays
- Turnaround time: Typically same day for a poster, but can be next day in busy periods
- Pricing: For high quality A3-A0 sized posters on satin 200gsm paper, prices range from £5.60 to £27.70. Please contact the business directly as prices will vary depending on the colour coverage of your poster.

#### Fineprint - Digital Printing &amp; Thesis Binding

- Located within QUB grounds
- Offers free poster delivery to QUB/Belfast accommodation
- Website: https://finebind.co.uk/printing/
- Phone: +4428 9030 1962
- Email: info@finebind.co.uk
- Address: Queen’s University, University Rd, Belfast, BT7 1NN
- Opening hours: 9am-5pm Monday to Thursday, 9am-4.30pm on Fridays, closed Saturdays and Sundays
- Turnaround time: 24 hours
- Pricing: Prices vary depending on the size of your poster. Please contact the business directly for an exact quote, but standard prices for posters printed on 190gsm silk art paper are: A3 - £2, A2 - £9, A1 - £12, A0 - £24

#### Northside Graphics

- About 15 minutes’ drive from QUB, but posters can also be ordered for delivery
- Website: https://northsidegraphics.com/
- Phone: +4428 9022 2111
- Email: info@northsidegraphics.com
- Address: Units 5 &amp; 6 Roundtower Industrial Estate, 145-147 Dargan Crescent, Belfast, BT3 9JP
- Turnaround time: 24 hours
- Opening hours: 9am-5.30pm Monday to Friday, closed Saturdays and Sundays
- Pricing: Posters cost £15+VAT