---
title: "`r paste(params$PSSlot,': ',params$Track)`"
execute: 
  echo: false
  
format: 
  html:
    page-layout: full
  
params:
  PSSlot: "Parallel Session 1"
  Track: "T1"
---

```{r}
#| include: false

# libraries --------------------------------------------------------------------
library(googlesheets4)
library(tidyverse)
library(DT)
# data -------------------------------------------------------------------------
isre24_program_communications <-
  read_sheet("https://docs.google.com/spreadsheets/d/1IXNmqqwtPi70zxuf4q6QTpIsFi4anOuSm4RZySt_m7A")

isre24_track <- isre24_program_communications |>
  filter(PSSlot == params$PSSlot) |>
  filter(Track == params$Track) |> 
  arrange(StartTime)
```

```{r}
track_details <- isre24_track |> 
  mutate(Time = paste(format(min(StartTime), format = "%H:%M"), "-", format(max(EndTime), format = "%H:%M"))) |> 
  select(Track, Type = TYPE, Title = SessionTitle, Time, Room, Abstract = SymposiaAbstract) |> 
  distinct() |> 
  t() |> 
  as.data.frame() |> 
  rownames_to_column()

if (track_details[track_details$rowname == "Type", "V1"] != "Symposium") {
  track_details <- filter(track_details, rowname != "Abstract")
}
  
track_details |>
  datatable(
    colnames = NULL,
    rownames = FALSE,
    extensions = 'Responsive',
    options = list(
      responsive = list(details = list(target =  1)),
      dom = 't',
      pageLength = -1,
      ordering = FALSE
      )
    ) |>
  formatStyle(colnames(track_details), fontSize = '100%') |>
  formatStyle("rowname", color = 'white', backgroundColor = '#D6000D', fontWeight = 'bold')
```

```{r}
isre24_track |>
  select(Title = Paper.Title, Time, Authors, Abstract) |>
  pivot_longer(!Title) |>
  datatable(
    colnames = NULL,
    rownames = FALSE,
    fillContainer = FALSE,
    extensions = c('Responsive', 'RowGroup'),
    options = list(
      scrollX = TRUE,
      responsive = list(details = list(target =  c(1,2))),
      dom = 't',
      pageLength = -1,
      ordering = FALSE,
      rowGroup = list(dataSrc = 0),
      columnDefs = list(
        list(width = '50px', targets = 1),
        list(width = '300px', targets = 2),
        list(visible = FALSE, targets = 0)
      )
    )
  )
```

